sudo: false
language: node_js
node_js:
  - "10"
  - "12"
  - "14"
cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - npm install codecov -g
  - npm run test
after_success:
  - codecov
